version: '3.8'

services:
  app:
    build: app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery_worker:
    build: app
    command: celery -A app.tasks.send_email_task worker --loglevel=info
    depends_on:
      - redis
